name = "Convex1d"
uuid = "d65ab6ab-6660-44ea-a7a3-f3acdcb1c2e6"
authors = ["Jan Weidner <jw3126@gmail.com>"]
version = "0.1.1"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
